export const pokemonSprites = {
  simisage: ["/pokemon-assets/simisage.gif"],
  espeon: ["/pokemon-assets/espeon.gif"],
  garchomp: [
    "/pokemon-assets/garchomp-4.gif",
    "/pokemon-assets/garchomp-5.gif",
    "/pokemon-assets/garchomp-2.gif",
    "/pokemon-assets/garchomp-3.gif",
    "/pokemon-assets/garchomp-f.gif",
    "/pokemon-assets/garchomp-mega.gif",
    "/pokemon-assets/garchomp.gif",
  ],
  pikachu: [
    "/pokemon-assets/pikachu-2.gif",
    "/pokemon-assets/pikachu-3.gif",
    "/pokemon-assets/pikachu-f.gif",
    "/pokemon-assets/pikachu-4.gif",
    "/pokemon-assets/pikachu-5.gif",
    "/pokemon-assets/pikachu.gif",
  ],
  mantyke: ["/pokemon-assets/mantyke.gif"],
  aipom: ["/pokemon-assets/aipom-f.gif", "/pokemon-assets/aipom.gif"],
  vivillon: [
    "/pokemon-assets/vivillon-fancy.gif",
    "/pokemon-assets/vivillon-continental.gif",
    "/pokemon-assets/vivillon-archipelago.gif",
    "/pokemon-assets/vivillon-meadow.gif",
    "/pokemon-assets/vivillon-monsoon.gif",
    "/pokemon-assets/vivillon-elegant.gif",
    "/pokemon-assets/vivillon-ocean.gif",
    "/pokemon-assets/vivillon-polar.gif",
    "/pokemon-assets/vivillon-savannah.gif",
    "/pokemon-assets/vivillon-river.gif",
    "/pokemon-assets/vivillon-pokeball.gif",
    "/pokemon-assets/vivillon-highplains.gif",
    "/pokemon-assets/vivillon-tundra.gif",
    "/pokemon-assets/vivillon-sandstorm.gif",
    "/pokemon-assets/vivillon-modern.gif",
    "/pokemon-assets/vivillon-sun.gif",
    "/pokemon-assets/vivillon-marine.gif",
    "/pokemon-assets/vivillon.gif",
    "/pokemon-assets/vivillon-garden.gif",
    "/pokemon-assets/vivillon-jungle.gif",
  ],
  exploud: ["/pokemon-assets/exploud.gif"],
  jumpluff: [
    "/pokemon-assets/jumpluff-3.gif",
    "/pokemon-assets/jumpluff-2.gif",
    "/pokemon-assets/jumpluff.gif",
  ],
  malamar: [
    "/pokemon-assets/malamar.gif",
    "/pokemon-assets/malamar-3.gif",
    "/pokemon-assets/malamar-2.gif",
  ],
  slaking: ["/pokemon-assets/slaking.gif"],
  sentret: [
    "/pokemon-assets/sentret-2.gif",
    "/pokemon-assets/sentret-3.gif",
    "/pokemon-assets/sentret.gif",
  ],
  gengar: [
    "/pokemon-assets/gengar-2.gif",
    "/pokemon-assets/gengar-3.gif",
    "/pokemon-assets/gengar-mega.gif",
    "/pokemon-assets/gengar.gif",
  ],
  pelipper: [
    "/pokemon-assets/pelipper.gif",
    "/pokemon-assets/pelipper-3.gif",
    "/pokemon-assets/pelipper-2.gif",
  ],
  solrock: ["/pokemon-assets/solrock.gif"],
  paras: ["/pokemon-assets/paras.gif"],
  hoppip: [
    "/pokemon-assets/hoppip-3.gif",
    "/pokemon-assets/hoppip-2.gif",
    "/pokemon-assets/hoppip.gif",
  ],
  hitmonlee: ["/pokemon-assets/hitmonlee.gif"],
  starly: ["/pokemon-assets/starly-f.gif", "/pokemon-assets/starly.gif"],
  noctowl: ["/pokemon-assets/noctowl.gif"],
  seadra: ["/pokemon-assets/seadra.gif"],
  spheal: ["/pokemon-assets/spheal.gif"],
  patrat: ["/pokemon-assets/patrat.gif"],
  lapras: [
    "/pokemon-assets/lapras-2.gif",
    "/pokemon-assets/lapras-3.gif",
    "/pokemon-assets/lapras.gif",
  ],
  ralts: ["/pokemon-assets/ralts.gif"],
  lotad: ["/pokemon-assets/lotad.gif"],
  goodra: [
    "/pokemon-assets/goodra-4.gif",
    "/pokemon-assets/goodra-5.gif",
    "/pokemon-assets/goodra-2.gif",
    "/pokemon-assets/goodra-3.gif",
    "/pokemon-assets/goodra.gif",
  ],
  eelektross: ["/pokemon-assets/eelektross.gif"],
  palpitoad: ["/pokemon-assets/palpitoad.gif"],
  poliwhirl: ["/pokemon-assets/poliwhirl.gif"],
  tangrowth: [
    "/pokemon-assets/tangrowth.gif",
    "/pokemon-assets/tangrowth-f.gif",
  ],
  unown: [
    "/pokemon-assets/unown-interrogation.gif",
    "/pokemon-assets/unown-foxtrot.gif",
    "/pokemon-assets/unown-papa.gif",
    "/pokemon-assets/unown-juliet.gif",
    "/pokemon-assets/unown-bravo.gif",
    "/pokemon-assets/unown-charlie.gif",
    "/pokemon-assets/unown-lima.gif",
    "/pokemon-assets/unown-exclamation.gif",
    "/pokemon-assets/unown-hotel.gif",
    "/pokemon-assets/unown-kilo.gif",
    "/pokemon-assets/unown-zulu.gif",
    "/pokemon-assets/unown-echo.gif",
    "/pokemon-assets/unown.gif",
    "/pokemon-assets/unown-november.gif",
    "/pokemon-assets/unown-oscar.gif",
    "/pokemon-assets/unown-yankee.gif",
    "/pokemon-assets/unown-whiskey.gif",
    "/pokemon-assets/unown-victor.gif",
    "/pokemon-assets/unown-sierra.gif",
    "/pokemon-assets/unown-romeo.gif",
    "/pokemon-assets/unown-quebec.gif",
    "/pokemon-assets/unown-tango.gif",
    "/pokemon-assets/unown-delta.gif",
    "/pokemon-assets/unown-xray.gif",
    "/pokemon-assets/unown-golf.gif",
    "/pokemon-assets/unown-mike.gif",
    "/pokemon-assets/unown-uniform.gif",
    "/pokemon-assets/unown-india.gif",
  ],
  slurpuff: [
    "/pokemon-assets/slurpuff.gif",
    "/pokemon-assets/slurpuff-2.gif",
    "/pokemon-assets/slurpuff-3.gif",
  ],
  registeel: ["/pokemon-assets/registeel.gif"],
  jellicent: [
    "/pokemon-assets/jellicent-f.gif",
    "/pokemon-assets/jellicent.gif",
  ],
  zorua: [
    "/pokemon-assets/zorua-3.gif",
    "/pokemon-assets/zorua-2.gif",
    "/pokemon-assets/zorua.gif",
  ],
  steelix: ["/pokemon-assets/steelix-f.gif", "/pokemon-assets/steelix.gif"],
  arcanine: ["/pokemon-assets/arcanine.gif"],
  absol: [
    "/pokemon-assets/absol-3.gif",
    "/pokemon-assets/absol-2.gif",
    "/pokemon-assets/absol.gif",
    "/pokemon-assets/absol-mega.gif",
  ],
  bronzor: ["/pokemon-assets/bronzor.gif"],
  aerodactyl: [
    "/pokemon-assets/aerodactyl.gif",
    "/pokemon-assets/aerodactyl-mega.gif",
    "/pokemon-assets/aerodactyl-2.gif",
    "/pokemon-assets/aerodactyl-3.gif",
  ],
  sharpedo: ["/pokemon-assets/sharpedo.gif"],
  flabebe: [
    "/pokemon-assets/flabebe.gif",
    "/pokemon-assets/flabebe-blue.gif",
    "/pokemon-assets/flabebe-orange.gif",
    "/pokemon-assets/flabebe-yellow.gif",
    "/pokemon-assets/flabebe-white.gif",
  ],
  kyogre: ["/pokemon-assets/kyogre.gif"],
  sylveon: ["/pokemon-assets/sylveon.gif"],
  "mime-jr": ["/pokemon-assets/mime_jr.gif"],
  pancham: ["/pokemon-assets/pancham.gif"],
  golbat: [
    "/pokemon-assets/golbat-f.gif",
    "/pokemon-assets/golbat-2.gif",
    "/pokemon-assets/golbat-3.gif",
    "/pokemon-assets/golbat.gif",
  ],
  magikarp: [
    "/pokemon-assets/magikarp-f.gif",
    "/pokemon-assets/magikarp-2.gif",
    "/pokemon-assets/magikarp.gif",
  ],
  armaldo: ["/pokemon-assets/armaldo.gif"],
  dwebble: ["/pokemon-assets/dwebble.gif"],
  joltik: ["/pokemon-assets/joltik.gif"],
  metagross: ["/pokemon-assets/metagross.gif"],
  maractus: ["/pokemon-assets/maractus.gif"],
  feebas: ["/pokemon-assets/feebas.gif"],
  haxorus: [
    "/pokemon-assets/haxorus-4.gif",
    "/pokemon-assets/haxorus-3.gif",
    "/pokemon-assets/haxorus-2.gif",
    "/pokemon-assets/haxorus.gif",
  ],
  quilladin: [
    "/pokemon-assets/quilladin.gif",
    "/pokemon-assets/quilladin-3.gif",
    "/pokemon-assets/quilladin-2.gif",
  ],
  staryu: ["/pokemon-assets/staryu.gif"],
  chimchar: ["/pokemon-assets/chimchar.gif"],
  empoleon: ["/pokemon-assets/empoleon.gif"],
  muk: ["/pokemon-assets/muk.gif"],
  diancie: ["/pokemon-assets/diancie.gif"],
  prinplup: ["/pokemon-assets/prinplup.gif"],
  fearow: ["/pokemon-assets/fearow.gif"],
  helioptile: ["/pokemon-assets/helioptile.gif"],
  pansear: ["/pokemon-assets/pansear.gif"],
  rhyperior: [
    "/pokemon-assets/rhyperior.gif",
    "/pokemon-assets/rhyperior-f.gif",
  ],
  phione: ["/pokemon-assets/phione.gif"],
  spearow: ["/pokemon-assets/spearow.gif"],
  happiny: ["/pokemon-assets/happiny.gif"],
  lickitung: [
    "/pokemon-assets/lickitung-3.gif",
    "/pokemon-assets/lickitung-2.gif",
    "/pokemon-assets/lickitung.gif",
  ],
  gorebyss: ["/pokemon-assets/gorebyss.gif"],
  rattata: ["/pokemon-assets/rattata-f.gif", "/pokemon-assets/rattata.gif"],
  klink: ["/pokemon-assets/klink.gif"],
  farfetchd: ["/pokemon-assets/farfetchd.gif"],
  zoroark: [
    "/pokemon-assets/zoroark-3.gif",
    "/pokemon-assets/zoroark-2.gif",
    "/pokemon-assets/zoroark.gif",
  ],
  diglett: ["/pokemon-assets/diglett.gif"],
  krokorok: ["/pokemon-assets/krokorok.gif"],
  scizor: [
    "/pokemon-assets/scizor.gif",
    "/pokemon-assets/scizor-f.gif",
    "/pokemon-assets/scizor-3.gif",
    "/pokemon-assets/scizor-2.gif",
    "/pokemon-assets/scizor-mega.gif",
  ],
  herdier: ["/pokemon-assets/herdier.gif"],
  noivern: [
    "/pokemon-assets/noivern.gif",
    "/pokemon-assets/noivern-3.gif",
    "/pokemon-assets/noivern-2.gif",
  ],
  whiscash: ["/pokemon-assets/whiscash.gif"],
  tynamo: ["/pokemon-assets/tynamo.gif"],
  slowbro: [
    "/pokemon-assets/slowbro.gif",
    "/pokemon-assets/slowbro-3.gif",
    "/pokemon-assets/slowbro-2.gif",
  ],
  vaporeon: [
    "/pokemon-assets/vaporeon.gif",
    "/pokemon-assets/vaporeon-4.gif",
    "/pokemon-assets/vaporeon-3.gif",
    "/pokemon-assets/vaporeon-2.gif",
  ],
  frogadier: [
    "/pokemon-assets/frogadier-2.gif",
    "/pokemon-assets/frogadier-3.gif",
    "/pokemon-assets/frogadier.gif",
  ],
  porygon: ["/pokemon-assets/porygon-z.gif", "/pokemon-assets/porygon.gif"],
  glalie: ["/pokemon-assets/glalie.gif"],
  numel: ["/pokemon-assets/numel.gif", "/pokemon-assets/numel-f.gif"],
  shaymin: ["/pokemon-assets/shaymin.gif", "/pokemon-assets/shaymin-sky.gif"],
  remoraid: ["/pokemon-assets/remoraid.gif"],
  deerling: [
    "/pokemon-assets/deerling-summer.gif",
    "/pokemon-assets/deerling.gif",
    "/pokemon-assets/deerling-winter.gif",
    "/pokemon-assets/deerling-autumn.gif",
  ],
  skarmory: ["/pokemon-assets/skarmory.gif"],
  deoxys: [
    "/pokemon-assets/deoxys-speed.gif",
    "/pokemon-assets/deoxys-attack.gif",
    "/pokemon-assets/deoxys-defense.gif",
    "/pokemon-assets/deoxys.gif",
  ],
  hitmontop: [
    "/pokemon-assets/hitmontop.gif",
    "/pokemon-assets/hitmontop-marked.gif",
    "/pokemon-assets/hitmontop-4.gif",
    "/pokemon-assets/hitmontop-3.gif",
    "/pokemon-assets/hitmontop-2.gif",
  ],
  greninja: [
    "/pokemon-assets/greninja.gif",
    "/pokemon-assets/greninja-4.gif",
    "/pokemon-assets/greninja-3.gif",
    "/pokemon-assets/greninja-2.gif",
  ],
  bronzong: ["/pokemon-assets/bronzong.gif"],
  abomasnow: [
    "/pokemon-assets/abomasnow.gif",
    "/pokemon-assets/abomasnow-4.gif",
    "/pokemon-assets/abomasnow-f.gif",
    "/pokemon-assets/abomasnow-mega.gif",
    "/pokemon-assets/abomasnow-3.gif",
    "/pokemon-assets/abomasnow-2.gif",
  ],
  throh: ["/pokemon-assets/throh.gif"],
  unfezant: ["/pokemon-assets/unfezant-f.gif", "/pokemon-assets/unfezant.gif"],
  glaceon: [
    "/pokemon-assets/glaceon-4.gif",
    "/pokemon-assets/glaceon.gif",
    "/pokemon-assets/glaceon-2.gif",
    "/pokemon-assets/glaceon-3.gif",
  ],
  kyurem: [
    "/pokemon-assets/kyurem-white.gif",
    "/pokemon-assets/kyurem-black.gif",
    "/pokemon-assets/kyurem.gif",
  ],
  machoke: ["/pokemon-assets/machoke.gif"],
  lunatone: ["/pokemon-assets/lunatone.gif"],
  arceus: ["/pokemon-assets/arceus.gif"],
  bastiodon: ["/pokemon-assets/bastiodon.gif"],
  mandibuzz: ["/pokemon-assets/mandibuzz.gif"],
  ducklett: ["/pokemon-assets/ducklett.gif"],
  latios: ["/pokemon-assets/latios-mega.gif", "/pokemon-assets/latios.gif"],
  plusle: ["/pokemon-assets/plusle.gif"],
  poliwag: ["/pokemon-assets/poliwag.gif"],
  crustle: ["/pokemon-assets/crustle.gif"],
  kecleon: ["/pokemon-assets/kecleon.gif"],
  shuppet: [
    "/pokemon-assets/shuppet.gif",
    "/pokemon-assets/shuppet-2.gif",
    "/pokemon-assets/shuppet-3.gif",
  ],
  basculin: [
    "/pokemon-assets/basculin-blue.gif",
    "/pokemon-assets/basculin.gif",
  ],
  dugtrio: ["/pokemon-assets/dugtrio.gif"],
  flygon: ["/pokemon-assets/flygon.gif"],
  marill: ["/pokemon-assets/marill.gif"],
  torchic: ["/pokemon-assets/torchic.gif", "/pokemon-assets/torchic-f.gif"],
  treecko: ["/pokemon-assets/treecko.gif"],
  dunsparce: [
    "/pokemon-assets/dunsparce.gif",
    "/pokemon-assets/dunsparce-2.gif",
    "/pokemon-assets/dunsparce-3.gif",
  ],
  kabutops: ["/pokemon-assets/kabutops.gif"],
  weavile: ["/pokemon-assets/weavile-f.gif", "/pokemon-assets/weavile.gif"],
  cacnea: ["/pokemon-assets/cacnea.gif"],
  slugma: ["/pokemon-assets/slugma.gif"],
  jirachi: ["/pokemon-assets/jirachi.gif"],
  oddish: ["/pokemon-assets/oddish.gif"],
  lumineon: ["/pokemon-assets/lumineon-f.gif", "/pokemon-assets/lumineon.gif"],
  cranidos: ["/pokemon-assets/cranidos.gif"],
  pidgeot: [
    "/pokemon-assets/pidgeot.gif",
    "/pokemon-assets/pidgeot-2.gif",
    "/pokemon-assets/pidgeot-3.gif",
  ],
  litwick: ["/pokemon-assets/litwick.gif"],
  raticate: ["/pokemon-assets/raticate-f.gif", "/pokemon-assets/raticate.gif"],
  drilbur: ["/pokemon-assets/drilbur.gif"],
  sandslash: ["/pokemon-assets/sandslash.gif"],
  duskull: ["/pokemon-assets/duskull.gif"],
  druddigon: [
    "/pokemon-assets/druddigon-3.gif",
    "/pokemon-assets/druddigon-2.gif",
    "/pokemon-assets/druddigon.gif",
  ],
  xatu: [
    "/pokemon-assets/xatu-f.gif",
    "/pokemon-assets/xatu-3.gif",
    "/pokemon-assets/xatu-2.gif",
    "/pokemon-assets/xatu.gif",
  ],
  pichu: [
    "/pokemon-assets/pichu.gif",
    "/pokemon-assets/pichu-2.gif",
    "/pokemon-assets/pichu-3.gif",
  ],
  wailord: [
    "/pokemon-assets/wailord-2.gif",
    "/pokemon-assets/wailord-3.gif",
    "/pokemon-assets/wailord.gif",
  ],
  chansey: ["/pokemon-assets/chansey.gif"],
  ledian: [
    "/pokemon-assets/ledian-2.gif",
    "/pokemon-assets/ledian-3.gif",
    "/pokemon-assets/ledian-f.gif",
    "/pokemon-assets/ledian.gif",
  ],
  wobbuffet: [
    "/pokemon-assets/wobbuffet-f.gif",
    "/pokemon-assets/wobbuffet.gif",
  ],
  camerupt: ["/pokemon-assets/camerupt.gif", "/pokemon-assets/camerupt-f.gif"],
  whirlipede: ["/pokemon-assets/whirlipede.gif"],
  lampent: [
    "/pokemon-assets/lampent-2.gif",
    "/pokemon-assets/lampent-3.gif",
    "/pokemon-assets/lampent.gif",
  ],
  floette: [
    "/pokemon-assets/floette-yellow.gif",
    "/pokemon-assets/floette.gif",
    "/pokemon-assets/floette-white.gif",
    "/pokemon-assets/floette-eternal.gif",
    "/pokemon-assets/floette-orange.gif",
    "/pokemon-assets/floette-blue.gif",
  ],
  kangaskhan: [
    "/pokemon-assets/kangaskhan.gif",
    "/pokemon-assets/kangaskhan-mega.gif",
  ],
  ivysaur: [
    "/pokemon-assets/ivysaur-3.gif",
    "/pokemon-assets/ivysaur-2.gif",
    "/pokemon-assets/ivysaur.gif",
  ],
  avalugg: [
    "/pokemon-assets/avalugg-2.gif",
    "/pokemon-assets/avalugg-3.gif",
    "/pokemon-assets/avalugg.gif",
  ],
  chingling: ["/pokemon-assets/chingling.gif"],
  chespin: [
    "/pokemon-assets/chespin-3.gif",
    "/pokemon-assets/chespin-2.gif",
    "/pokemon-assets/chespin.gif",
  ],
  zekrom: ["/pokemon-assets/zekrom.gif"],
  golduck: ["/pokemon-assets/golduck.gif"],
  haunter: [
    "/pokemon-assets/haunter.gif",
    "/pokemon-assets/haunter-2.gif",
    "/pokemon-assets/haunter-3.gif",
  ],
  ferroseed: [
    "/pokemon-assets/ferroseed.gif",
    "/pokemon-assets/ferroseed-2.gif",
    "/pokemon-assets/ferroseed-3.gif",
  ],
  barbaracle: ["/pokemon-assets/barbaracle.gif"],
  salamence: [
    "/pokemon-assets/salamence.gif",
    "/pokemon-assets/salamence-2.gif",
    "/pokemon-assets/salamence-3.gif",
    "/pokemon-assets/salamence-4.gif",
    "/pokemon-assets/salamence-5.gif",
  ],
  squirtle: [
    "/pokemon-assets/squirtle-3.gif",
    "/pokemon-assets/squirtle-2.gif",
    "/pokemon-assets/squirtle.gif",
  ],
  tepig: ["/pokemon-assets/tepig.gif"],
  aron: [
    "/pokemon-assets/aron.gif",
    "/pokemon-assets/aron-3.gif",
    "/pokemon-assets/aron-2.gif",
  ],
  sudowoodo: [
    "/pokemon-assets/sudowoodo-f.gif",
    "/pokemon-assets/sudowoodo.gif",
  ],
  riolu: ["/pokemon-assets/riolu.gif"],
  clauncher: [
    "/pokemon-assets/clauncher.gif",
    "/pokemon-assets/clauncher-3.gif",
    "/pokemon-assets/clauncher-2.gif",
  ],
  zapdos: ["/pokemon-assets/zapdos.gif"],
  aurorus: [
    "/pokemon-assets/aurorus-2.gif",
    "/pokemon-assets/aurorus-3.gif",
    "/pokemon-assets/aurorus.gif",
  ],
  klang: ["/pokemon-assets/klang.gif"],
  milotic: ["/pokemon-assets/milotic.gif", "/pokemon-assets/milotic-f.gif"],
  mienshao: ["/pokemon-assets/mienshao.gif"],
  politoed: ["/pokemon-assets/politoed.gif", "/pokemon-assets/politoed-f.gif"],
  togepi: ["/pokemon-assets/togepi.gif"],
  ponyta: ["/pokemon-assets/ponyta.gif"],
  raichu: [
    "/pokemon-assets/raichu.gif",
    "/pokemon-assets/raichu-3.gif",
    "/pokemon-assets/raichu-2.gif",
    "/pokemon-assets/raichu-f.gif",
  ],
  combee: [
    "/pokemon-assets/combee-f.gif",
    "/pokemon-assets/combee-2.gif",
    "/pokemon-assets/combee-3.gif",
    "/pokemon-assets/combee.gif",
  ],
  luxray: [
    "/pokemon-assets/luxray-f.gif",
    "/pokemon-assets/luxray-2.gif",
    "/pokemon-assets/luxray-3.gif",
    "/pokemon-assets/luxray.gif",
  ],
  slakoth: ["/pokemon-assets/slakoth.gif"],
  hitmonchan: ["/pokemon-assets/hitmonchan.gif"],
  caterpie: ["/pokemon-assets/caterpie.gif", "/pokemon-assets/caterpie-2.gif"],
  psyduck: [
    "/pokemon-assets/psyduck.gif",
    "/pokemon-assets/psyduck-2.gif",
    "/pokemon-assets/psyduck-3.gif",
  ],
  sawsbuck: [
    "/pokemon-assets/sawsbuck-winter.gif",
    "/pokemon-assets/sawsbuck-summer.gif",
    "/pokemon-assets/sawsbuck-autumn.gif",
    "/pokemon-assets/sawsbuck.gif",
  ],
  combusken: [
    "/pokemon-assets/combusken-f.gif",
    "/pokemon-assets/combusken.gif",
  ],
  spinda: ["/pokemon-assets/spinda-2.gif", "/pokemon-assets/spinda.gif"],
  snover: ["/pokemon-assets/snover.gif", "/pokemon-assets/snover-f.gif"],
  fraxure: [
    "/pokemon-assets/fraxure.gif",
    "/pokemon-assets/fraxure-2.gif",
    "/pokemon-assets/fraxure-3.gif",
  ],
  solosis: ["/pokemon-assets/solosis.gif"],
  sewaddle: ["/pokemon-assets/sewaddle.gif"],
  mawile: [
    "/pokemon-assets/mawile.gif",
    "/pokemon-assets/mawile-3.gif",
    "/pokemon-assets/mawile-2.gif",
    "/pokemon-assets/mawile-mega.gif",
  ],
  gabite: ["/pokemon-assets/gabite-f.gif", "/pokemon-assets/gabite.gif"],
  teddiursa: ["/pokemon-assets/teddiursa.gif"],
  darumaka: ["/pokemon-assets/darumaka.gif"],
  piplup: ["/pokemon-assets/piplup.gif"],
  mantine: ["/pokemon-assets/mantine.gif"],
  vanilluxe: ["/pokemon-assets/vanilluxe.gif"],
  cubchoo: ["/pokemon-assets/cubchoo.gif"],
  mamoswine: [
    "/pokemon-assets/mamoswine-f.gif",
    "/pokemon-assets/mamoswine.gif",
  ],
  simipour: ["/pokemon-assets/simipour.gif"],
  seismitoad: ["/pokemon-assets/seismitoad.gif"],
  manaphy: ["/pokemon-assets/manaphy.gif"],
  bunnelby: ["/pokemon-assets/bunnelby.gif"],
  zygarde: [
    "/pokemon-assets/zygarde.gif",
    "/pokemon-assets/zygarde-3.gif",
    "/pokemon-assets/zygarde-2.gif",
    "/pokemon-assets/zygarde-5.gif",
    "/pokemon-assets/zygarde-4.gif",
  ],
  rufflet: [
    "/pokemon-assets/rufflet.gif",
    "/pokemon-assets/rufflet-2.gif",
    "/pokemon-assets/rufflet-3.gif",
  ],
  medicham: [
    "/pokemon-assets/medicham-f.gif",
    "/pokemon-assets/medicham-mega.gif",
    "/pokemon-assets/medicham.gif",
  ],
  klinklang: ["/pokemon-assets/klinklang.gif"],
  mothim: ["/pokemon-assets/mothim.gif"],
  corsola: ["/pokemon-assets/corsola.gif"],
  roserade: ["/pokemon-assets/roserade.gif", "/pokemon-assets/roserade-f.gif"],
  weezing: ["/pokemon-assets/weezing.gif"],
  omanyte: ["/pokemon-assets/omanyte.gif"],
  swirlix: [
    "/pokemon-assets/swirlix-3.gif",
    "/pokemon-assets/swirlix-2.gif",
    "/pokemon-assets/swirlix.gif",
  ],
  burmy: [
    "/pokemon-assets/burmy-sandy.gif",
    "/pokemon-assets/burmy-trash.gif",
    "/pokemon-assets/burmy.gif",
    "/pokemon-assets/burmy-2.gif",
  ],
  heliolisk: ["/pokemon-assets/heliolisk.gif"],
  carbink: ["/pokemon-assets/carbink.gif"],
  shiftry: ["/pokemon-assets/shiftry.gif", "/pokemon-assets/shiftry-f.gif"],
  vibrava: ["/pokemon-assets/vibrava.gif"],
  sliggoo: ["/pokemon-assets/sliggoo.gif", "/pokemon-assets/sliggoo-2.gif"],
  seaking: ["/pokemon-assets/seaking-f.gif", "/pokemon-assets/seaking.gif"],
  heracross: [
    "/pokemon-assets/heracross-f.gif",
    "/pokemon-assets/heracross-mega.gif",
    "/pokemon-assets/heracross.gif",
  ],
  chatot: ["/pokemon-assets/chatot.gif"],
  jigglypuff: [
    "/pokemon-assets/jigglypuff.gif",
    "/pokemon-assets/jigglypuff-3.gif",
    "/pokemon-assets/jigglypuff-2.gif",
  ],
  swampert: ["/pokemon-assets/swampert.gif"],
  excadrill: ["/pokemon-assets/excadrill.gif"],
  togetic: ["/pokemon-assets/togetic.gif"],
  kakuna: ["/pokemon-assets/kakuna-2.gif", "/pokemon-assets/kakuna.gif"],
  "mr.-mime": [
    "/pokemon-assets/mr._mime.gif",
    "/pokemon-assets/mr._mime-2.gif",
    "/pokemon-assets/mr._mime-3.gif",
  ],
  forretress: ["/pokemon-assets/forretress.gif"],
  dragalge: [
    "/pokemon-assets/dragalge-2.gif",
    "/pokemon-assets/dragalge-3.gif",
    "/pokemon-assets/dragalge.gif",
  ],
  bisharp: ["/pokemon-assets/bisharp.gif"],
  feraligatr: ["/pokemon-assets/feraligatr.gif"],
  loudred: ["/pokemon-assets/loudred.gif"],
  victreebel: ["/pokemon-assets/victreebel.gif"],
  trapinch: ["/pokemon-assets/trapinch-2.gif", "/pokemon-assets/trapinch.gif"],
  gulpin: ["/pokemon-assets/gulpin-f.gif", "/pokemon-assets/gulpin.gif"],
  onix: ["/pokemon-assets/onix.gif"],
  nidorina: ["/pokemon-assets/nidorina.gif"],
  venonat: ["/pokemon-assets/venonat.gif"],
  thundurus: [
    "/pokemon-assets/thundurus.gif",
    "/pokemon-assets/thundurus-therian.gif",
  ],
  spinarak: ["/pokemon-assets/spinarak.gif"],
  venusaur: [
    "/pokemon-assets/venusaur-mega.gif",
    "/pokemon-assets/venusaur.gif",
    "/pokemon-assets/venusaur-f.gif",
  ],
  pachirisu: [
    "/pokemon-assets/pachirisu-f.gif",
    "/pokemon-assets/pachirisu.gif",
  ],
  buizel: ["/pokemon-assets/buizel.gif", "/pokemon-assets/buizel-f.gif"],
  mightyena: ["/pokemon-assets/mightyena.gif"],
  tranquill: ["/pokemon-assets/tranquill.gif"],
  xerneas: [
    "/pokemon-assets/xerneas-active.gif",
    "/pokemon-assets/xerneas.gif",
    "/pokemon-assets/xerneas-2.gif",
  ],
  lilligant: ["/pokemon-assets/lilligant.gif"],
  minccino: ["/pokemon-assets/minccino.gif"],
  tornadus: [
    "/pokemon-assets/tornadus-therian.gif",
    "/pokemon-assets/tornadus.gif",
  ],
  vulpix: ["/pokemon-assets/vulpix.gif"],
  clawitzer: [
    "/pokemon-assets/clawitzer.gif",
    "/pokemon-assets/clawitzer-3.gif",
    "/pokemon-assets/clawitzer-2.gif",
  ],
  pumpkaboo: [
    "/pokemon-assets/pumpkaboo-small.gif",
    "/pokemon-assets/pumpkaboo.gif",
    "/pokemon-assets/pumpkaboo-large.gif",
    "/pokemon-assets/pumpkaboo-super.gif",
  ],
  hippowdon: [
    "/pokemon-assets/hippowdon-f.gif",
    "/pokemon-assets/hippowdon.gif",
  ],
  shuckle: ["/pokemon-assets/shuckle.gif"],
  rayquaza: ["/pokemon-assets/rayquaza.gif"],
  sigilyph: [
    "/pokemon-assets/sigilyph-2.gif",
    "/pokemon-assets/sigilyph-3.gif",
    "/pokemon-assets/sigilyph.gif",
  ],
  doduo: [
    "/pokemon-assets/doduo.gif",
    "/pokemon-assets/doduo-3.gif",
    "/pokemon-assets/doduo-2.gif",
    "/pokemon-assets/doduo-f.gif",
  ],
  ferrothorn: [
    "/pokemon-assets/ferrothorn.gif",
    "/pokemon-assets/ferrothorn-4.gif",
    "/pokemon-assets/ferrothorn-3.gif",
    "/pokemon-assets/ferrothorn-2.gif",
  ],
  misdreavus: ["/pokemon-assets/misdreavus.gif"],
  kingdra: ["/pokemon-assets/kingdra.gif"],
  baltoy: ["/pokemon-assets/baltoy.gif"],
  ledyba: [
    "/pokemon-assets/ledyba.gif",
    "/pokemon-assets/ledyba-2.gif",
    "/pokemon-assets/ledyba-3.gif",
    "/pokemon-assets/ledyba-f.gif",
  ],
  kricketune: [
    "/pokemon-assets/kricketune.gif",
    "/pokemon-assets/kricketune-f.gif",
  ],
  giratina: [
    "/pokemon-assets/giratina-origin.gif",
    "/pokemon-assets/giratina.gif",
  ],
  skrelp: [
    "/pokemon-assets/skrelp.gif",
    "/pokemon-assets/skrelp-2.gif",
    "/pokemon-assets/skrelp-3.gif",
  ],
  rhydon: ["/pokemon-assets/rhydon-f.gif", "/pokemon-assets/rhydon.gif"],
  altaria: [
    "/pokemon-assets/altaria-3.gif",
    "/pokemon-assets/altaria-2.gif",
    "/pokemon-assets/altaria.gif",
  ],
  sableye: [
    "/pokemon-assets/sableye-2.gif",
    "/pokemon-assets/sableye-3.gif",
    "/pokemon-assets/sableye-4.gif",
    "/pokemon-assets/sableye.gif",
  ],
  hawlucha: ["/pokemon-assets/hawlucha.gif"],
  lairon: [
    "/pokemon-assets/lairon-3.gif",
    "/pokemon-assets/lairon-2.gif",
    "/pokemon-assets/lairon.gif",
  ],
  yanma: ["/pokemon-assets/yanma.gif"],
  talonflame: [
    "/pokemon-assets/talonflame-2.gif",
    "/pokemon-assets/talonflame-3.gif",
    "/pokemon-assets/talonflame.gif",
  ],
  lugia: ["/pokemon-assets/lugia.gif"],
  wailmer: [
    "/pokemon-assets/wailmer-3.gif",
    "/pokemon-assets/wailmer-2.gif",
    "/pokemon-assets/wailmer.gif",
  ],
  amoonguss: [
    "/pokemon-assets/amoonguss-3.gif",
    "/pokemon-assets/amoonguss-2.gif",
    "/pokemon-assets/amoonguss-4.gif",
    "/pokemon-assets/amoonguss.gif",
  ],
  exeggcute: ["/pokemon-assets/exeggcute.gif"],
  ursaring: ["/pokemon-assets/ursaring-f.gif", "/pokemon-assets/ursaring.gif"],
  slowking: ["/pokemon-assets/slowking.gif"],
  carvanha: ["/pokemon-assets/carvanha.gif", "/pokemon-assets/carvanha-2.gif"],
  emolga: ["/pokemon-assets/emolga.gif"],
  vespiquen: ["/pokemon-assets/vespiquen.gif"],
  leavanny: ["/pokemon-assets/leavanny.gif"],
  ludicolo: [
    "/pokemon-assets/ludicolo-3.gif",
    "/pokemon-assets/ludicolo-2.gif",
    "/pokemon-assets/ludicolo-f.gif",
    "/pokemon-assets/ludicolo.gif",
  ],
  florges: [
    "/pokemon-assets/florges-white.gif",
    "/pokemon-assets/florges-yellow.gif",
    "/pokemon-assets/florges-blue.gif",
    "/pokemon-assets/florges.gif",
    "/pokemon-assets/florges-orange.gif",
  ],
  sceptile: ["/pokemon-assets/sceptile.gif"],
  azurill: ["/pokemon-assets/azurill.gif"],
  houndoom: [
    "/pokemon-assets/houndoom-f.gif",
    "/pokemon-assets/houndoom-mega.gif",
    "/pokemon-assets/houndoom.gif",
  ],
  drifloon: ["/pokemon-assets/drifloon.gif"],
  bayleef: ["/pokemon-assets/bayleef.gif"],
  clefairy: ["/pokemon-assets/clefairy.gif"],
  staravia: ["/pokemon-assets/staravia.gif", "/pokemon-assets/staravia-f.gif"],
  linoone: ["/pokemon-assets/linoone.gif"],
  staraptor: [
    "/pokemon-assets/staraptor-f.gif",
    "/pokemon-assets/staraptor.gif",
  ],
  finneon: ["/pokemon-assets/finneon-f.gif", "/pokemon-assets/finneon.gif"],
  panpour: ["/pokemon-assets/panpour.gif"],
  "nidoran-m": ["/pokemon-assets/nidoran_m.gif"],
  meloetta: [
    "/pokemon-assets/meloetta.gif",
    "/pokemon-assets/meloetta-pirouette.gif",
  ],
  toxicroak: [
    "/pokemon-assets/toxicroak-f.gif",
    "/pokemon-assets/toxicroak-2.gif",
    "/pokemon-assets/toxicroak-3.gif",
    "/pokemon-assets/toxicroak.gif",
  ],
  scatterbug: ["/pokemon-assets/scatterbug.gif"],
  rotom: [
    "/pokemon-assets/rotom-fan.gif",
    "/pokemon-assets/rotom.gif",
    "/pokemon-assets/rotom-2.gif",
    "/pokemon-assets/rotom-3.gif",
    "/pokemon-assets/rotom-heat.gif",
    "/pokemon-assets/rotom-4.gif",
    "/pokemon-assets/rotom-wash.gif",
    "/pokemon-assets/rotom-frost.gif",
    "/pokemon-assets/rotom-mow.gif",
  ],
  vanillite: [
    "/pokemon-assets/vanillite.gif",
    "/pokemon-assets/vanillite-2.gif",
  ],
  grimer: ["/pokemon-assets/grimer.gif"],
  beheeyem: ["/pokemon-assets/beheeyem.gif"],
  spiritomb: ["/pokemon-assets/spiritomb.gif"],
  chikorita: ["/pokemon-assets/chikorita.gif"],
  leafeon: [
    "/pokemon-assets/leafeon.gif",
    "/pokemon-assets/leafeon-4.gif",
    "/pokemon-assets/leafeon-2.gif",
    "/pokemon-assets/leafeon-3.gif",
  ],
  flareon: [
    "/pokemon-assets/flareon-4.gif",
    "/pokemon-assets/flareon-2.gif",
    "/pokemon-assets/flareon-3.gif",
    "/pokemon-assets/flareon.gif",
  ],
  turtwig: ["/pokemon-assets/turtwig.gif"],
  breloom: ["/pokemon-assets/breloom.gif"],
  tyrogue: [
    "/pokemon-assets/tyrogue-3.gif",
    "/pokemon-assets/tyrogue-2.gif",
    "/pokemon-assets/tyrogue.gif",
  ],
  zweilous: [
    "/pokemon-assets/zweilous.gif",
    "/pokemon-assets/zweilous-3.gif",
    "/pokemon-assets/zweilous-2.gif",
  ],
  larvesta: [
    "/pokemon-assets/larvesta-2.gif",
    "/pokemon-assets/larvesta-3.gif",
    "/pokemon-assets/larvesta.gif",
  ],
  celebi: ["/pokemon-assets/celebi.gif"],
  bagon: [
    "/pokemon-assets/bagon-3.gif",
    "/pokemon-assets/bagon-2.gif",
    "/pokemon-assets/bagon.gif",
  ],
  axew: [
    "/pokemon-assets/axew.gif",
    "/pokemon-assets/axew-3.gif",
    "/pokemon-assets/axew-2.gif",
  ],
  stunfisk: [
    "/pokemon-assets/stunfisk-2.gif",
    "/pokemon-assets/stunfisk-3.gif",
    "/pokemon-assets/stunfisk.gif",
  ],
  darkrai: ["/pokemon-assets/darkrai.gif"],
  spoink: ["/pokemon-assets/spoink-2.gif", "/pokemon-assets/spoink.gif"],
  hydreigon: [
    "/pokemon-assets/hydreigon-2.gif",
    "/pokemon-assets/hydreigon-3.gif",
    "/pokemon-assets/hydreigon-4.gif",
    "/pokemon-assets/hydreigon-5.gif",
    "/pokemon-assets/hydreigon.gif",
  ],
  pangoro: ["/pokemon-assets/pangoro.gif"],
  gourgeist: [
    "/pokemon-assets/gourgeist-small.gif",
    "/pokemon-assets/gourgeist-large.gif",
    "/pokemon-assets/gourgeist.gif",
    "/pokemon-assets/gourgeist-2.gif",
    "/pokemon-assets/gourgeist-3.gif",
    "/pokemon-assets/gourgeist-super.gif",
  ],
  ambipom: ["/pokemon-assets/ambipom-f.gif", "/pokemon-assets/ambipom.gif"],
  swinub: ["/pokemon-assets/swinub.gif"],
  smoochum: [
    "/pokemon-assets/smoochum-2.gif",
    "/pokemon-assets/smoochum-3.gif",
    "/pokemon-assets/smoochum.gif",
  ],
  ninetales: [
    "/pokemon-assets/ninetales.gif",
    "/pokemon-assets/ninetales-4.gif",
    "/pokemon-assets/ninetales-3.gif",
    "/pokemon-assets/ninetales-2.gif",
  ],
  wingull: [
    "/pokemon-assets/wingull-2.gif",
    "/pokemon-assets/wingull-3.gif",
    "/pokemon-assets/wingull.gif",
  ],
  blitzle: ["/pokemon-assets/blitzle.gif"],
  pawniard: [
    "/pokemon-assets/pawniard.gif",
    "/pokemon-assets/pawniard-3.gif",
    "/pokemon-assets/pawniard-2.gif",
  ],
  dewgong: ["/pokemon-assets/dewgong.gif"],
  blaziken: [
    "/pokemon-assets/blaziken-mega.gif",
    "/pokemon-assets/blaziken.gif",
    "/pokemon-assets/blaziken-f.gif",
    "/pokemon-assets/blaziken-2.gif",
    "/pokemon-assets/blaziken-3.gif",
    "/pokemon-assets/blaziken-4.gif",
  ],
  krabby: ["/pokemon-assets/krabby.gif"],
  castform: [
    "/pokemon-assets/castform-snowy.gif",
    "/pokemon-assets/castform.gif",
    "/pokemon-assets/castform-sunny.gif",
    "/pokemon-assets/castform-rainy.gif",
  ],
  vigoroth: ["/pokemon-assets/vigoroth.gif"],
  volcarona: [
    "/pokemon-assets/volcarona.gif",
    "/pokemon-assets/volcarona-2.gif",
    "/pokemon-assets/volcarona-3.gif",
    "/pokemon-assets/volcarona-4.gif",
  ],
  tentacruel: ["/pokemon-assets/tentacruel.gif"],
  charmeleon: [
    "/pokemon-assets/charmeleon-2.gif",
    "/pokemon-assets/charmeleon-3.gif",
    "/pokemon-assets/charmeleon.gif",
  ],
  croagunk: [
    "/pokemon-assets/croagunk.gif",
    "/pokemon-assets/croagunk-f.gif",
    "/pokemon-assets/croagunk-3.gif",
    "/pokemon-assets/croagunk-2.gif",
  ],
  gothitelle: ["/pokemon-assets/gothitelle.gif"],
  krookodile: ["/pokemon-assets/krookodile.gif"],
  porygon2: ["/pokemon-assets/porygon2.gif"],
  charmander: [
    "/pokemon-assets/charmander-3.gif",
    "/pokemon-assets/charmander-2.gif",
    "/pokemon-assets/charmander.gif",
  ],
  blastoise: [
    "/pokemon-assets/blastoise-4.gif",
    "/pokemon-assets/blastoise-mega.gif",
    "/pokemon-assets/blastoise-3.gif",
    "/pokemon-assets/blastoise-2.gif",
    "/pokemon-assets/blastoise.gif",
  ],
  regice: ["/pokemon-assets/regice.gif"],
  volbeat: ["/pokemon-assets/volbeat.gif"],
  grovyle: ["/pokemon-assets/grovyle.gif"],
  meowth: ["/pokemon-assets/meowth.gif"],
  bellsprout: ["/pokemon-assets/bellsprout.gif"],
  luvdisc: ["/pokemon-assets/luvdisc.gif"],
  nincada: ["/pokemon-assets/nincada.gif"],
  horsea: ["/pokemon-assets/horsea.gif"],
  garbodor: ["/pokemon-assets/garbodor.gif"],
  kricketot: [
    "/pokemon-assets/kricketot.gif",
    "/pokemon-assets/kricketot-f.gif",
  ],
  togekiss: ["/pokemon-assets/togekiss.gif"],
  terrakion: ["/pokemon-assets/terrakion.gif"],
  jynx: ["/pokemon-assets/jynx.gif"],
  pinsir: ["/pokemon-assets/pinsir-mega.gif", "/pokemon-assets/pinsir.gif"],
  roselia: ["/pokemon-assets/roselia-f.gif", "/pokemon-assets/roselia.gif"],
  yamask: ["/pokemon-assets/yamask.gif"],
  lugiad: ["/pokemon-assets/lugiad.gif"],
  electrode: ["/pokemon-assets/electrode.gif"],
  metang: ["/pokemon-assets/metang.gif"],
  donphan: ["/pokemon-assets/donphan.gif", "/pokemon-assets/donphan-f.gif"],
  fennekin: ["/pokemon-assets/fennekin.gif"],
  kabuto: ["/pokemon-assets/kabuto.gif"],
  braviary: ["/pokemon-assets/braviary.gif"],
  swoobat: ["/pokemon-assets/swoobat.gif"],
  magmar: ["/pokemon-assets/magmar.gif"],
  lombre: [
    "/pokemon-assets/lombre.gif",
    "/pokemon-assets/lombre-3.gif",
    "/pokemon-assets/lombre-2.gif",
  ],
  sunkern: ["/pokemon-assets/sunkern.gif"],
  golem: ["/pokemon-assets/golem.gif"],
  wormadam: [
    "/pokemon-assets/wormadam-2.gif",
    "/pokemon-assets/wormadam-sandy.gif",
    "/pokemon-assets/wormadam-trash.gif",
    "/pokemon-assets/wormadam.gif",
  ],
  charizard: [
    "/pokemon-assets/charizard-megax.gif",
    "/pokemon-assets/charizard-megay.gif",
    "/pokemon-assets/charizard.gif",
    "/pokemon-assets/charizard-2.gif",
    "/pokemon-assets/charizard-3.gif",
    "/pokemon-assets/charizard-4.gif",
  ],
  durant: ["/pokemon-assets/durant.gif"],
  aromatisse: [
    "/pokemon-assets/aromatisse-3.gif",
    "/pokemon-assets/aromatisse-2.gif",
    "/pokemon-assets/aromatisse.gif",
  ],
  skitty: [
    "/pokemon-assets/skitty-3.gif",
    "/pokemon-assets/skitty-2.gif",
    "/pokemon-assets/skitty.gif",
  ],
  deino: ["/pokemon-assets/deino.gif"],
  pansage: ["/pokemon-assets/pansage.gif"],
  cobalion: ["/pokemon-assets/cobalion.gif"],
  croconaw: ["/pokemon-assets/croconaw.gif"],
  dewott: ["/pokemon-assets/dewott.gif"],
  accelgor: [
    "/pokemon-assets/accelgor-3.gif",
    "/pokemon-assets/accelgor-2.gif",
    "/pokemon-assets/accelgor.gif",
  ],
  cofagrigus: ["/pokemon-assets/cofagrigus.gif"],
  meganium: ["/pokemon-assets/meganium-f.gif", "/pokemon-assets/meganium.gif"],
  spewpa: ["/pokemon-assets/spewpa.gif", "/pokemon-assets/spewpa-2.gif"],
  furret: [
    "/pokemon-assets/furret.gif",
    "/pokemon-assets/furret-3.gif",
    "/pokemon-assets/furret-2.gif",
  ],
  grumpig: ["/pokemon-assets/grumpig.gif"],
  clefable: ["/pokemon-assets/clefable.gif"],
  furfrou: ["/pokemon-assets/furfrou.gif"],
  virizion: ["/pokemon-assets/virizion.gif"],
  spritzee: [
    "/pokemon-assets/spritzee.gif",
    "/pokemon-assets/spritzee-2.gif",
    "/pokemon-assets/spritzee-3.gif",
  ],
  rhyhorn: ["/pokemon-assets/rhyhorn-f.gif", "/pokemon-assets/rhyhorn.gif"],
  blissey: ["/pokemon-assets/blissey.gif"],
  simisear: ["/pokemon-assets/simisear.gif"],
  natu: ["/pokemon-assets/natu.gif"],
  venomoth: ["/pokemon-assets/venomoth.gif"],
  phantump: [
    "/pokemon-assets/phantump.gif",
    "/pokemon-assets/phantump-2.gif",
    "/pokemon-assets/phantump-3.gif",
  ],
  kirlia: [
    "/pokemon-assets/kirlia.gif",
    "/pokemon-assets/kirlia-2.gif",
    "/pokemon-assets/kirlia-3.gif",
  ],
  omastar: ["/pokemon-assets/omastar.gif"],
  scolipede: ["/pokemon-assets/scolipede.gif"],
  landorus: [
    "/pokemon-assets/landorus-therian.gif",
    "/pokemon-assets/landorus.gif",
  ],
  karrablast: [
    "/pokemon-assets/karrablast.gif",
    "/pokemon-assets/karrablast-2.gif",
  ],
  torkoal: ["/pokemon-assets/torkoal.gif"],
  hoothoot: ["/pokemon-assets/hoothoot.gif"],
  hoopa: ["/pokemon-assets/hoopa.gif"],
  beautifly: [
    "/pokemon-assets/beautifly-f.gif",
    "/pokemon-assets/beautifly.gif",
  ],
  amaura: [
    "/pokemon-assets/amaura-3.gif",
    "/pokemon-assets/amaura-2.gif",
    "/pokemon-assets/amaura.gif",
  ],
  relicanth: [
    "/pokemon-assets/relicanth.gif",
    "/pokemon-assets/relicanth-f.gif",
  ],
  wynaut: ["/pokemon-assets/wynaut.gif"],
  victini: ["/pokemon-assets/victini.gif"],
  cherrim: [
    "/pokemon-assets/cherrim-sunshine.gif",
    "/pokemon-assets/cherrim.gif",
  ],
  cloyster: ["/pokemon-assets/cloyster.gif"],
  cradily: ["/pokemon-assets/cradily.gif"],
  drifblim: ["/pokemon-assets/drifblim.gif"],
  mudkip: ["/pokemon-assets/mudkip.gif"],
  timburr: ["/pokemon-assets/timburr.gif"],
  gallade: [
    "/pokemon-assets/gallade-2.gif",
    "/pokemon-assets/gallade-3.gif",
    "/pokemon-assets/gallade.gif",
  ],
  trevenant: [
    "/pokemon-assets/trevenant-3.gif",
    "/pokemon-assets/trevenant-2.gif",
    "/pokemon-assets/trevenant.gif",
  ],
  shellder: ["/pokemon-assets/shellder.gif"],
  shelgon: [
    "/pokemon-assets/shelgon-3.gif",
    "/pokemon-assets/shelgon-2.gif",
    "/pokemon-assets/shelgon.gif",
  ],
  trubbish: ["/pokemon-assets/trubbish.gif"],
  floatzel: ["/pokemon-assets/floatzel-f.gif", "/pokemon-assets/floatzel.gif"],
  bibarel: ["/pokemon-assets/bibarel-f.gif", "/pokemon-assets/bibarel.gif"],
  uxie: ["/pokemon-assets/uxie.gif"],
  aegislash: [
    "/pokemon-assets/aegislash-2.gif",
    "/pokemon-assets/aegislash.gif",
    "/pokemon-assets/aegislash-blade.gif",
  ],
  suicune: ["/pokemon-assets/suicune.gif"],
  marshtomp: ["/pokemon-assets/marshtomp.gif"],
  kingler: ["/pokemon-assets/kingler.gif"],
  shroomish: ["/pokemon-assets/shroomish.gif"],
  bergmite: [
    "/pokemon-assets/bergmite.gif",
    "/pokemon-assets/bergmite-2.gif",
    "/pokemon-assets/bergmite-3.gif",
  ],
  lanturn: ["/pokemon-assets/lanturn.gif"],
  bonsly: ["/pokemon-assets/bonsly.gif"],
  gligar: ["/pokemon-assets/gligar.gif", "/pokemon-assets/gligar-f.gif"],
  ekans: ["/pokemon-assets/ekans.gif"],
  mew: ["/pokemon-assets/mew.gif"],
  manectric: [
    "/pokemon-assets/manectric-mega.gif",
    "/pokemon-assets/manectric.gif",
  ],
  slowpoke: [
    "/pokemon-assets/slowpoke.gif",
    "/pokemon-assets/slowpoke-2.gif",
    "/pokemon-assets/slowpoke-3.gif",
  ],
  articuno: ["/pokemon-assets/articuno.gif"],
  pyroar: [
    "/pokemon-assets/pyroar-f.gif",
    "/pokemon-assets/pyroar.gif",
    "/pokemon-assets/pyroar-2.gif",
  ],
  magmortar: ["/pokemon-assets/magmortar.gif"],
  meowstic: [
    "/pokemon-assets/meowstic.gif",
    "/pokemon-assets/meowstic-f.gif",
    "/pokemon-assets/meowstic-2.gif",
    "/pokemon-assets/meowstic-3.gif",
  ],
  parasect: ["/pokemon-assets/parasect.gif"],
  dedenne: ["/pokemon-assets/dedenne.gif"],
  raikou: ["/pokemon-assets/raikou.gif"],
  infernape: ["/pokemon-assets/infernape.gif"],
  taillow: ["/pokemon-assets/taillow.gif"],
  kadabra: [
    "/pokemon-assets/kadabra-2.gif",
    "/pokemon-assets/kadabra-3.gif",
    "/pokemon-assets/kadabra-f.gif",
    "/pokemon-assets/kadabra.gif",
  ],
  pidove: ["/pokemon-assets/pidove.gif"],
  bulbasaur: [
    "/pokemon-assets/bulbasaur.gif",
    "/pokemon-assets/bulbasaur-3.gif",
    "/pokemon-assets/bulbasaur-2.gif",
  ],
  inkay: [
    "/pokemon-assets/inkay-2.gif",
    "/pokemon-assets/inkay-3.gif",
    "/pokemon-assets/inkay.gif",
  ],
  banette: ["/pokemon-assets/banette.gif", "/pokemon-assets/banette-mega.gif"],
  starmie: ["/pokemon-assets/starmie.gif"],
  yanmega: ["/pokemon-assets/yanmega.gif"],
  escavalier: [
    "/pokemon-assets/escavalier-2.gif",
    "/pokemon-assets/escavalier-3.gif",
    "/pokemon-assets/escavalier.gif",
  ],
  sandshrew: ["/pokemon-assets/sandshrew.gif"],
  tyranitar: [
    "/pokemon-assets/tyranitar-mega.gif",
    "/pokemon-assets/tyranitar.gif",
  ],
  alakazam: [
    "/pokemon-assets/alakazam.gif",
    "/pokemon-assets/alakazam-mega.gif",
    "/pokemon-assets/alakazam-f.gif",
    "/pokemon-assets/alakazam-3.gif",
    "/pokemon-assets/alakazam-2.gif",
  ],
  palkia: ["/pokemon-assets/palkia.gif"],
  cresselia: ["/pokemon-assets/cresselia.gif"],
  regigigas: ["/pokemon-assets/regigigas.gif"],
  wooper: [
    "/pokemon-assets/wooper-2.gif",
    "/pokemon-assets/wooper-3.gif",
    "/pokemon-assets/wooper-f.gif",
    "/pokemon-assets/wooper.gif",
  ],
  zigzagoon: ["/pokemon-assets/zigzagoon.gif"],
  yveltal: ["/pokemon-assets/yveltal.gif"],
  archeops: [
    "/pokemon-assets/archeops-3.gif",
    "/pokemon-assets/archeops-2.gif",
    "/pokemon-assets/archeops.gif",
  ],
  petilil: ["/pokemon-assets/petilil.gif"],
  purugly: ["/pokemon-assets/purugly.gif"],
  torterra: ["/pokemon-assets/torterra.gif"],
  mareep: ["/pokemon-assets/mareep.gif"],
  froakie: [
    "/pokemon-assets/froakie.gif",
    "/pokemon-assets/froakie-2.gif",
    "/pokemon-assets/froakie-3.gif",
  ],
  bellossom: ["/pokemon-assets/bellossom.gif"],
  munna: ["/pokemon-assets/munna.gif"],
  shieldon: ["/pokemon-assets/shieldon.gif"],
  stoutland: ["/pokemon-assets/stoutland.gif"],
  tirtouga: ["/pokemon-assets/tirtouga.gif"],
  nidoking: ["/pokemon-assets/nidoking.gif"],
  makuhita: ["/pokemon-assets/makuhita.gif"],
  seviper: ["/pokemon-assets/seviper.gif"],
  nidoqueen: ["/pokemon-assets/nidoqueen.gif"],
  carracosta: ["/pokemon-assets/carracosta.gif"],
  huntail: ["/pokemon-assets/huntail.gif"],
  nosepass: ["/pokemon-assets/nosepass.gif"],
  vileplume: [
    "/pokemon-assets/vileplume-f.gif",
    "/pokemon-assets/vileplume.gif",
  ],
  skorupi: ["/pokemon-assets/skorupi.gif"],
  ampharos: [
    "/pokemon-assets/ampharos-mega.gif",
    "/pokemon-assets/ampharos.gif",
  ],
  quagsire: ["/pokemon-assets/quagsire-f.gif", "/pokemon-assets/quagsire.gif"],
  conkeldurr: ["/pokemon-assets/conkeldurr.gif"],
  goomy: [
    "/pokemon-assets/goomy-2.gif",
    "/pokemon-assets/goomy-3.gif",
    "/pokemon-assets/goomy.gif",
  ],
  luxio: [
    "/pokemon-assets/luxio.gif",
    "/pokemon-assets/luxio-2.gif",
    "/pokemon-assets/luxio-3.gif",
    "/pokemon-assets/luxio-f.gif",
  ],
  corphish: [
    "/pokemon-assets/corphish-3.gif",
    "/pokemon-assets/corphish-2.gif",
    "/pokemon-assets/corphish.gif",
  ],
  "nidoran-f": ["/pokemon-assets/nidoran_f.gif"],
  galvantula: ["/pokemon-assets/galvantula.gif"],
  binacle: ["/pokemon-assets/binacle.gif"],
  alomomola: [
    "/pokemon-assets/alomomola-3.gif",
    "/pokemon-assets/alomomola-2.gif",
    "/pokemon-assets/alomomola.gif",
  ],
  hippopotas: [
    "/pokemon-assets/hippopotas.gif",
    "/pokemon-assets/hippopotas-f.gif",
  ],
  crawdaunt: ["/pokemon-assets/crawdaunt.gif"],
  poliwrath: ["/pokemon-assets/poliwrath.gif"],
  magnemite: ["/pokemon-assets/magnemite.gif"],
  shellos: ["/pokemon-assets/shellos.gif", "/pokemon-assets/shellos-east.gif"],
  gothita: ["/pokemon-assets/gothita.gif"],
  budew: ["/pokemon-assets/budew.gif"],
  shinx: [
    "/pokemon-assets/shinx.gif",
    "/pokemon-assets/shinx-3.gif",
    "/pokemon-assets/shinx-2.gif",
    "/pokemon-assets/shinx-f.gif",
  ],
  serperior: ["/pokemon-assets/serperior.gif"],
  dratini: ["/pokemon-assets/dratini.gif"],
  mienfoo: ["/pokemon-assets/mienfoo.gif"],
  electrike: ["/pokemon-assets/electrike.gif"],
  reshiram: ["/pokemon-assets/reshiram.gif"],
  beedrill: ["/pokemon-assets/beedrill.gif"],
  fletchinder: ["/pokemon-assets/fletchinder.gif"],
  butterfree: [
    "/pokemon-assets/butterfree.gif",
    "/pokemon-assets/butterfree-f.gif",
  ],
  heatran: ["/pokemon-assets/heatran.gif"],
  gliscor: ["/pokemon-assets/gliscor.gif"],
  machop: ["/pokemon-assets/machop.gif"],
  cyndaquil: ["/pokemon-assets/cyndaquil.gif"],
  swellow: ["/pokemon-assets/swellow.gif"],
  phanpy: ["/pokemon-assets/phanpy.gif"],
  duosion: ["/pokemon-assets/duosion.gif"],
  scraggy: ["/pokemon-assets/scraggy.gif"],
  shedinja: ["/pokemon-assets/shedinja.gif"],
  sawk: ["/pokemon-assets/sawk.gif"],
  shelmet: ["/pokemon-assets/shelmet.gif"],
  latias: ["/pokemon-assets/latias.gif", "/pokemon-assets/latias-mega.gif"],
  ariados: ["/pokemon-assets/ariados.gif"],
  fletchling: ["/pokemon-assets/fletchling.gif"],
  roggenrola: ["/pokemon-assets/roggenrola.gif"],
  azelf: ["/pokemon-assets/azelf.gif"],
  heatmor: ["/pokemon-assets/heatmor.gif"],
  meditite: ["/pokemon-assets/meditite.gif", "/pokemon-assets/meditite-f.gif"],
  liepard: ["/pokemon-assets/liepard.gif"],
  musharna: ["/pokemon-assets/musharna.gif"],
  cubone: ["/pokemon-assets/cubone.gif"],
  octillery: [
    "/pokemon-assets/octillery.gif",
    "/pokemon-assets/octillery-f.gif",
  ],
  gible: ["/pokemon-assets/gible.gif", "/pokemon-assets/gible-f.gif"],
  chandelure: ["/pokemon-assets/chandelure.gif"],
  wigglytuff: ["/pokemon-assets/wigglytuff.gif"],
  "venusaur.16": ["/pokemon-assets/venusaur.16.gif"],
  rampardos: ["/pokemon-assets/rampardos.gif"],
  larvitar: ["/pokemon-assets/larvitar.gif"],
  koffing: ["/pokemon-assets/koffing.gif"],
  dusclops: ["/pokemon-assets/dusclops.gif"],
  ditto: ["/pokemon-assets/ditto.gif"],
  scrafty: ["/pokemon-assets/scrafty.gif"],
  chinchou: ["/pokemon-assets/chinchou.gif"],
  litleo: ["/pokemon-assets/litleo.gif"],
  dusknoir: ["/pokemon-assets/dusknoir.gif"],
  sunflora: ["/pokemon-assets/sunflora.gif"],
  flaaffy: ["/pokemon-assets/flaaffy.gif"],
  delcatty: ["/pokemon-assets/delcatty.gif"],
  gastly: ["/pokemon-assets/gastly.gif"],
  gastrodon: [
    "/pokemon-assets/gastrodon.gif",
    "/pokemon-assets/gastrodon-east.gif",
  ],
  growlithe: ["/pokemon-assets/growlithe.gif"],
  cleffa: ["/pokemon-assets/cleffa.gif"],
  nuzleaf: ["/pokemon-assets/nuzleaf-f.gif", "/pokemon-assets/nuzleaf.gif"],
  granbull: ["/pokemon-assets/granbull.gif"],
  whismur: ["/pokemon-assets/whismur.gif"],
  cryogonal: ["/pokemon-assets/cryogonal.gif"],
  rapidash: ["/pokemon-assets/rapidash.gif"],
  stantler: ["/pokemon-assets/stantler.gif"],
  snorunt: ["/pokemon-assets/snorunt-2.gif", "/pokemon-assets/snorunt.gif"],
  cascoon: ["/pokemon-assets/cascoon.gif"],
  aggron: [
    "/pokemon-assets/aggron-2.gif",
    "/pokemon-assets/aggron.gif",
    "/pokemon-assets/aggron-3.gif",
    "/pokemon-assets/aggron-mega.gif",
  ],
  surskit: ["/pokemon-assets/surskit.gif"],
  snubbull: ["/pokemon-assets/snubbull.gif"],
  monferno: ["/pokemon-assets/monferno.gif"],
  sandile: ["/pokemon-assets/sandile.gif"],
  pignite: ["/pokemon-assets/pignite.gif"],
  piloswine: [
    "/pokemon-assets/piloswine-f.gif",
    "/pokemon-assets/piloswine.gif",
  ],
  tangela: ["/pokemon-assets/tangela.gif"],
  doublade: ["/pokemon-assets/doublade.gif"],
  arbok: ["/pokemon-assets/arbok.gif"],
  lucario: [
    "/pokemon-assets/lucario.gif",
    "/pokemon-assets/lucario-mega.gif",
    "/pokemon-assets/lucario-2.gif",
    "/pokemon-assets/lucario-3.gif",
    "/pokemon-assets/lucario-4.gif",
  ],
  venipede: ["/pokemon-assets/venipede.gif"],
  vullaby: ["/pokemon-assets/vullaby.gif"],
  elekid: ["/pokemon-assets/elekid.gif"],
  pupitar: ["/pokemon-assets/pupitar.gif"],
  grotle: ["/pokemon-assets/grotle.gif"],
  dragonair: [
    "/pokemon-assets/dragonair.gif",
    "/pokemon-assets/dragonair-2.gif",
    "/pokemon-assets/dragonair-3.gif",
  ],
  typhlosion: ["/pokemon-assets/typhlosion.gif"],
  zebstrika: ["/pokemon-assets/zebstrika.gif"],
  machamp: ["/pokemon-assets/machamp.gif"],
  ninjask: ["/pokemon-assets/ninjask.gif"],
  azumarill: [
    "/pokemon-assets/azumarill.gif",
    "/pokemon-assets/azumarill-2.gif",
    "/pokemon-assets/azumarill-3.gif",
  ],
  audino: ["/pokemon-assets/audino.gif"],
  dodrio: [
    "/pokemon-assets/dodrio.gif",
    "/pokemon-assets/dodrio-3.gif",
    "/pokemon-assets/dodrio-2.gif",
    "/pokemon-assets/dodrio-f.gif",
  ],
  diggersby: ["/pokemon-assets/diggersby.gif"],
  chimecho: ["/pokemon-assets/chimecho.gif"],
  cottonee: ["/pokemon-assets/cottonee.gif"],
  silcoon: ["/pokemon-assets/silcoon.gif"],
  swalot: ["/pokemon-assets/swalot-f.gif", "/pokemon-assets/swalot.gif"],
  dialga: ["/pokemon-assets/dialga.gif"],
  tauros: ["/pokemon-assets/tauros.gif"],
  totodile: ["/pokemon-assets/totodile.gif"],
  sneasel: ["/pokemon-assets/sneasel-f.gif", "/pokemon-assets/sneasel.gif"],
  gloom: ["/pokemon-assets/gloom-f.gif", "/pokemon-assets/gloom.gif"],
  tropius: ["/pokemon-assets/tropius.gif"],
  bouffalant: ["/pokemon-assets/bouffalant.gif"],
  mewtwo: [
    "/pokemon-assets/mewtwo.gif",
    "/pokemon-assets/mewtwo-megay.gif",
    "/pokemon-assets/mewtwo-megax.gif",
  ],
  eevee: [
    "/pokemon-assets/eevee.gif",
    "/pokemon-assets/eevee-3.gif",
    "/pokemon-assets/eevee-2.gif",
  ],
  buneary: ["/pokemon-assets/buneary.gif"],
  crobat: [
    "/pokemon-assets/crobat-3.gif",
    "/pokemon-assets/crobat.gif",
    "/pokemon-assets/crobat-2.gif",
  ],
  ho: ["/pokemon-assets/ho-oh.gif"],
  archen: ["/pokemon-assets/archen.gif"],
  woobat: ["/pokemon-assets/woobat.gif"],
  gyarados: [
    "/pokemon-assets/gyarados-2.gif",
    "/pokemon-assets/gyarados-3.gif",
    "/pokemon-assets/gyarados.gif",
    "/pokemon-assets/gyarados-f.gif",
    "/pokemon-assets/gyarados-mega.gif",
  ],
  wartortle: [
    "/pokemon-assets/wartortle.gif",
    "/pokemon-assets/wartortle-3.gif",
    "/pokemon-assets/wartortle-2.gif",
  ],
  noibat: ["/pokemon-assets/noibat.gif"],
  dragonite: [
    "/pokemon-assets/dragonite-4.gif",
    "/pokemon-assets/dragonite-5.gif",
    "/pokemon-assets/dragonite-2.gif",
    "/pokemon-assets/dragonite-3.gif",
    "/pokemon-assets/dragonite.gif",
  ],
  elgyem: ["/pokemon-assets/elgyem.gif"],
  bidoof: ["/pokemon-assets/bidoof.gif", "/pokemon-assets/bidoof-f.gif"],
  braixen: ["/pokemon-assets/braixen.gif"],
  cinccino: ["/pokemon-assets/cinccino.gif"],
  cacturne: ["/pokemon-assets/cacturne-f.gif", "/pokemon-assets/cacturne.gif"],
  keldeo: ["/pokemon-assets/keldeo-resolute.gif", "/pokemon-assets/keldeo.gif"],
  anorith: ["/pokemon-assets/anorith.gif"],
  wurmple: ["/pokemon-assets/wurmple.gif"],
  electabuzz: ["/pokemon-assets/electabuzz.gif"],
  tyrantrum: [
    "/pokemon-assets/tyrantrum-2.gif",
    "/pokemon-assets/tyrantrum-3.gif",
    "/pokemon-assets/tyrantrum.gif",
  ],
  "pikachu-f": [
    "/pokemon-assets/pikachu-f-3.gif",
    "/pokemon-assets/pikachu-f-2.gif",
    "/pokemon-assets/pikachu-f-5.gif",
    "/pokemon-assets/pikachu-f-4.gif",
  ],
  miltank: ["/pokemon-assets/miltank.gif"],
  pidgey: ["/pokemon-assets/pidgey.gif"],
  gurdurr: ["/pokemon-assets/gurdurr.gif"],
  gardevoir: [
    "/pokemon-assets/gardevoir-mega.gif",
    "/pokemon-assets/gardevoir-3.gif",
    "/pokemon-assets/gardevoir-2.gif",
    "/pokemon-assets/gardevoir.gif",
  ],
  chesnaught: [
    "/pokemon-assets/chesnaught-2.gif",
    "/pokemon-assets/chesnaught-3.gif",
    "/pokemon-assets/chesnaught.gif",
    "/pokemon-assets/chesnaught-4.gif",
  ],
  delphox: [
    "/pokemon-assets/delphox-4.gif",
    "/pokemon-assets/delphox-2.gif",
    "/pokemon-assets/delphox-3.gif",
    "/pokemon-assets/delphox.gif",
  ],
  tyrunt: ["/pokemon-assets/tyrunt.gif"],
  igglybuff: ["/pokemon-assets/igglybuff.gif"],
  qwilfish: ["/pokemon-assets/qwilfish.gif"],
  hypno: ["/pokemon-assets/hypno-f.gif", "/pokemon-assets/hypno.gif"],
  illumise: ["/pokemon-assets/illumise.gif"],
  mankey: ["/pokemon-assets/mankey.gif"],
  abra: ["/pokemon-assets/abra.gif", "/pokemon-assets/abra-2.gif"],
  goldeen: [
    "/pokemon-assets/goldeen.gif",
    "/pokemon-assets/goldeen-f.gif",
    "/pokemon-assets/goldeen-2.gif",
    "/pokemon-assets/goldeen-3.gif",
  ],
  munchlax: ["/pokemon-assets/munchlax.gif"],
  volcanion: ["/pokemon-assets/volcanion.gif"],
  purrloin: ["/pokemon-assets/purrloin.gif"],
  murkrow: ["/pokemon-assets/murkrow-f.gif", "/pokemon-assets/murkrow.gif"],
  walrein: ["/pokemon-assets/walrein.gif"],
  lillipup: ["/pokemon-assets/lillipup.gif"],
  skuntank: ["/pokemon-assets/skuntank.gif"],
  skiploom: [
    "/pokemon-assets/skiploom-2.gif",
    "/pokemon-assets/skiploom-3.gif",
    "/pokemon-assets/skiploom.gif",
  ],
  lickilicky: ["/pokemon-assets/lickilicky.gif"],
  espurr: ["/pokemon-assets/espurr.gif"],
  pidgeotto: ["/pokemon-assets/pidgeotto.gif"],
  tentacool: ["/pokemon-assets/tentacool.gif"],
  oshawott: ["/pokemon-assets/oshawott.gif"],
  watchog: ["/pokemon-assets/watchog.gif"],
  dustox: ["/pokemon-assets/dustox-f.gif", "/pokemon-assets/dustox.gif"],
  hariyama: ["/pokemon-assets/hariyama.gif"],
  nidorino: ["/pokemon-assets/nidorino.gif"],
  weedle: ["/pokemon-assets/weedle-2.gif", "/pokemon-assets/weedle.gif"],
  seel: ["/pokemon-assets/seel.gif"],
  weepinbell: ["/pokemon-assets/weepinbell.gif"],
  masquerain: ["/pokemon-assets/masquerain.gif"],
  swablu: ["/pokemon-assets/swablu.gif"],
  pineco: ["/pokemon-assets/pineco.gif"],
  graveler: ["/pokemon-assets/graveler.gif"],
  girafarig: [
    "/pokemon-assets/girafarig.gif",
    "/pokemon-assets/girafarig-f.gif",
  ],
  electivire: ["/pokemon-assets/electivire.gif"],
  poochyena: ["/pokemon-assets/poochyena.gif"],
  minun: ["/pokemon-assets/minun.gif"],
  primeape: ["/pokemon-assets/primeape.gif"],
  vanillish: ["/pokemon-assets/vanillish.gif"],
  carnivine: ["/pokemon-assets/carnivine.gif"],
  scyther: ["/pokemon-assets/scyther-f.gif", "/pokemon-assets/scyther.gif"],
  probopass: ["/pokemon-assets/probopass.gif"],
  darmanitan: [
    "/pokemon-assets/darmanitan.gif",
    "/pokemon-assets/darmanitan-zen.gif",
  ],
  smeargle: ["/pokemon-assets/smeargle.gif"],
  samurott: ["/pokemon-assets/samurott.gif"],
  magby: ["/pokemon-assets/magby.gif"],
  geodude: ["/pokemon-assets/geodude.gif"],
  foongus: ["/pokemon-assets/foongus.gif"],
  stunky: ["/pokemon-assets/stunky.gif"],
  swadloon: ["/pokemon-assets/swadloon.gif"],
  drapion: ["/pokemon-assets/drapion.gif"],
  delibird: ["/pokemon-assets/delibird.gif"],
  zubat: [
    "/pokemon-assets/zubat-f.gif",
    "/pokemon-assets/zubat.gif",
    "/pokemon-assets/zubat-2.gif",
    "/pokemon-assets/zubat-3.gif",
  ],
  klefki: ["/pokemon-assets/klefki.gif"],
  umbreon: ["/pokemon-assets/umbreon.gif"],
  magcargo: ["/pokemon-assets/magcargo.gif"],
  genesect: ["/pokemon-assets/genesect.gif"],
  boldore: ["/pokemon-assets/boldore.gif"],
  reuniclus: ["/pokemon-assets/reuniclus.gif"],
  froslass: ["/pokemon-assets/froslass.gif"],
  honedge: ["/pokemon-assets/honedge.gif"],
  servine: ["/pokemon-assets/servine.gif"],
  entei: ["/pokemon-assets/entei.gif"],
  barboach: ["/pokemon-assets/barboach.gif"],
  cherubi: ["/pokemon-assets/cherubi.gif"],
  regirock: ["/pokemon-assets/regirock.gif"],
  mismagius: ["/pokemon-assets/mismagius.gif"],
  voltorb: ["/pokemon-assets/voltorb.gif"],
  golett: ["/pokemon-assets/golett.gif"],
  snorlax: ["/pokemon-assets/snorlax.gif"],
  beartic: ["/pokemon-assets/beartic.gif"],
  persian: ["/pokemon-assets/persian.gif"],
  lopunny: ["/pokemon-assets/lopunny.gif"],
  snivy: ["/pokemon-assets/snivy.gif"],
  sealeo: ["/pokemon-assets/sealeo.gif"],
  houndour: ["/pokemon-assets/houndour.gif"],
  gothorita: ["/pokemon-assets/gothorita.gif"],
  eelektrik: ["/pokemon-assets/eelektrik.gif"],
  whimsicott: ["/pokemon-assets/whimsicott.gif"],
  quilava: ["/pokemon-assets/quilava.gif"],
  seedot: ["/pokemon-assets/seedot.gif"],
  skiddo: ["/pokemon-assets/skiddo.gif"],
  drowzee: ["/pokemon-assets/drowzee.gif"],
  clamperl: ["/pokemon-assets/clamperl.gif"],
  claydol: ["/pokemon-assets/claydol.gif"],
  lileep: ["/pokemon-assets/lileep.gif"],
  frillish: ["/pokemon-assets/frillish.gif", "/pokemon-assets/frillish-f.gif"],
  tympole: ["/pokemon-assets/tympole.gif"],
  honchkrow: ["/pokemon-assets/honchkrow.gif"],
  swanna: ["/pokemon-assets/swanna.gif"],
  zangoose: ["/pokemon-assets/zangoose.gif"],
  glameow: ["/pokemon-assets/glameow.gif"],
  magnezone: ["/pokemon-assets/magnezone.gif"],
  beldum: ["/pokemon-assets/beldum.gif"],
  metapod: ["/pokemon-assets/metapod.gif"],
  moltres: ["/pokemon-assets/moltres.gif"],
  jolteon: ["/pokemon-assets/jolteon.gif"],
  gogoat: ["/pokemon-assets/gogoat.gif"],
  golurk: ["/pokemon-assets/golurk.gif"],
  groudon: ["/pokemon-assets/groudon.gif"],
  exeggutor: ["/pokemon-assets/exeggutor.gif"],
  emboar: ["/pokemon-assets/emboar.gif"],
  gigalith: ["/pokemon-assets/gigalith.gif"],
  marowak: ["/pokemon-assets/marowak.gif"],
  mesprit: ["/pokemon-assets/mesprit.gif"],
  magneton: ["/pokemon-assets/magneton.gif"],
};

export type PokemonName = keyof typeof pokemonSprites;

export const pokemonNames = Object.keys(pokemonSprites);
